name: gopls
version: 0.8.0
summary: gopls, the Go Language Server
description: |
  gopls (pronounced "Go please") is the official Go language server
  developed by the Go team. It provides IDE features to any LSP-compatible
  editor.

base: core20
confinement: classic
grade: stable

apps:
  gopls:
    command: bin/gopls

parts:
  gopls:
    plugin: go
    source: https://github.com/golang/tools.git
    source-tag: gopls/v$SNAPCRAFT_PROJECT_VERSION
    source-subdir: gopls
    build-packages:
      - git
      - gcc
