name: gopls
adopt-info: gopls
summary: gopls, the Go Language Server
description: |
  gopls (pronounced "Go please") is the official Go language server
  developed by the Go team. It provides IDE features to any LSP-compatible
  editor.

base: core20
confinement: classic
grade: stable

apps:
  gopls:
    command: bin/gopls

parts:
  gopls:
    plugin: go
    source: https://github.com/golang/tools.git
    source-subdir: gopls
    build-packages:
      - git
      - gcc
    override-pull: |
      snapcraftctl pull
      lastTag=$(git describe --tags --always $(git rev-list --tags=gopls) | grep "gopls/v[0-9]\+.[0-9]\+.[0-9]\+$" | head -n 1)
      git checkout $lastTag
      snapcraftctl set-version $(echo $lastTag | sed 's/gopls\/v//')
