name: gopls
adopt-info: gopls
summary: gopls Language Server
description: |
  gopls (pronounced: "go please") is the official language server for the
  Go language.

  It is currently in alpha, so it is not stable. You can see more
  information about the status of gopls and its supported features
  [here](https://github.com/golang/tools/blob/master/gopls/doc/status.md).

base: core18
confinement: classic

apps:
  gopls:
    command: bin/gopls

parts:
  gopls:
    plugin: go
    go-packages:
      - golang.org/x/tools/gopls
    build-packages:
      - git
      - gcc
    override-pull: |
      snapcraftctl pull
      snapcraftctl set-version $(git -C ../go/src/golang.org/x/tools/gopls describe --tags | sed 's/gopls\/v//')
      snapcraftctl set-grade devel
